apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-deployment
  labels:
    app: blogapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp
  template:
    metadata:
      labels:
        app: blogapp
    spec:
      containers:
      - name: blogapp
        image: wbusolo/scacloudschool:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"  
---
kind: Service
apiVersion: v1
metadata:
  name: blogapp-service
spec:
  type: NodePort
  selector:
    app: blogapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30500
